#!/usr/bin/env python3
"""Emit an IDAPython script that applies maps/<target>/names.tsv.

usage: gen_ida.py <target_id> [min_tier]
writes work/<target>/ida_apply.py (run it in IDA via File > Script file; IDA 7.x-9.x).
Mangled names are set as-is; IDA demangles them for display.
"""
import csv
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths  # noqa: E402

TEMPLATE = '''# generated by tools/gen_ida.py for {target}; tiers <= {min_tier}
import idaapi, idc, ida_name, ida_funcs, ida_bytes

NAMES = [
{rows}]

base = idaapi.get_imagebase()
n = created = 0
for rva, kind, tier, mangled, chain in NAMES:
    ea = base + rva
    if kind == "func" and not ida_funcs.get_func(ea):
        ida_bytes.del_items(ea, 0, 1)
        idc.create_insn(ea)
        if ida_funcs.add_func(ea):
            created += 1
    if ida_name.set_name(ea, mangled, ida_name.SN_NOWARN | ida_name.SN_NOCHECK | ida_name.SN_FORCE):
        n += 1
    cmt = "homm4 tier %s | %s" % (tier, chain)
    if kind == "func" and ida_funcs.get_func(ea):
        idc.set_func_cmt(ea, cmt, 1)
    else:
        idc.set_cmt(ea, cmt, 1)
print("homm4: named %d, created %d functions" % (n, created))
'''


def main(target, min_tier="C"):
    with open(paths.maps(target, "names.tsv")) as f:
        rows = [r for r in csv.DictReader(f, delimiter="\t") if r["tier"] <= min_tier]
    body = "".join(f"    (0x{r['rva']}, {r['kind']!r}, {r['tier']!r}, {r['mangled']!r}, {r['chain']!r}),\n"
                   for r in rows)
    path = paths.work(target, "ida_apply.py")
    with open(path, "w") as f:
        f.write(TEMPLATE.format(target=target, min_tier=min_tier, rows=body))
    print(f"{len(rows)} names -> {path}", file=sys.stderr)


if __name__ == "__main__":
    main(*sys.argv[1:])
