#!/usr/bin/env python3
"""Emit an IDC script that applies maps/<target>/names.tsv.

usage: gen_ida.py <target_id> [min_tier]
writes work/<target>/ida_apply.idc (run it in IDA via File > Script file; IDC works in IDA Free too).
Mangled names are set as-is; IDA demangles them for display. Addresses assume the target.json image base.
"""
import csv
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths  # noqa: E402

CHUNK = 2000  # names per IDC function, to keep each one small

HEADER = '''// generated by tools/gen_ida.py for {target}; tiers <= {min_tier}
#include <idc.idc>

// name one address; creates the function first if kind is func and none covers it
static N(ea, is_func, name, cmt)
{{
    if (is_func && get_func_attr(ea, FUNCATTR_START) == BADADDR) {{
        del_items(ea, 0, 1);
        create_insn(ea);
        add_func(ea, BADADDR);
    }}
    auto ok = set_name(ea, name, 0x901);  // SN_NOCHECK | SN_NOWARN | SN_FORCE
    if (is_func && get_func_attr(ea, FUNCATTR_START) == ea)
        set_func_cmt(ea, cmt, 1);
    else
        set_cmt(ea, cmt, 1);
    return ok != 0;
}}
'''


def idc_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main(target, min_tier="C"):
    base = int(paths.target_meta(target)["image_base"], 16)
    with open(paths.maps(target, "names.tsv")) as f:
        rows = [r for r in csv.DictReader(f, delimiter="\t") if r["tier"] <= min_tier]
    lines = [f"    n = n + N(0x{base + int(r['rva'], 16):X}, {int(r['kind'] == 'func')}, {idc_str(r['name'])}, "
             + idc_str(f"homm4 tier {r['tier']} | {r['method']} {r['evidence']} (map {r['map_id']} {r['obj']})")
             + ");\n" for r in rows]
    out = [HEADER.format(target=target, min_tier=min_tier)]
    parts = range(0, len(lines), CHUNK)
    for i in parts:
        out.append(f"\nstatic part{i // CHUNK}()\n{{\n    auto n = 0;\n{''.join(lines[i:i + CHUNK])}    return n;\n}}\n")
    calls = "".join(f"    n = n + part{i // CHUNK}();\n" for i in parts)
    out.append(f'\nstatic main()\n{{\n    auto n = 0;\n{calls}    msg("homm4: named %d of {len(rows)}\\n", n);\n}}\n')
    path = paths.work(target, "ida_apply.idc")
    with open(path, "w") as f:
        f.write("".join(out))
    print(f"{len(rows)} names -> {path}", file=sys.stderr)


if __name__ == "__main__":
    main(*sys.argv[1:])
